In [4]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [5]:
df = pd.read_csv("veri_netflix.csv")

In [8]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   object
 2   title         6234 non-null   object
 3   director      4265 non-null   object
 4   cast          5664 non-null   object
 5   country       5758 non-null   object
 6   date_added    6223 non-null   object
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   object
 9   duration      6234 non-null   object
 10  listed_in     6234 non-null   object
 11  description   6234 non-null   object
dtypes: int64(2), object(10)
memory usage: 584.6+ KB

In [8]:
df.index

RangeIndex(start=0, stop=6234, step=1)

In [12]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [13]:
yeni_etiket = {'show_id':'show_nu','type':'tip','title':'isim',
               'director':'yönetmen','cast':'kadro','country':'ülke',
               'date_added':'eklenme_tarihi','release_year':'vizyon_tarihi',
               'rating':'kanal','duration':'süre','listed_in':'kategori',
               'description':'aciklama'}

In [14]:
df.rename(columns=yeni_etiket,inplace=True)

In [9]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [13]:
df.iloc[100]

show_nu                                                    81132443
tip                                                           Movie
isim                                                       Deliha 2
yönetmen                                                 Gupse Özay
kadro             Gupse Özay, Eda Ece, Aksel Bonfil, Derya Alabo...
ülke                                                         Turkey
eklenme_tarihi                                   September 27, 2019
vizyon_tarihi                                                  2018
kanal                                                         TV-PG
süre                                                        102 min
kategori                             Comedies, International Movies
aciklama          While chasing her dream of becoming a chef, Ze...
Name: 100, dtype: object

In [15]:
df.loc[100]

show_nu                                                    81132443
tip                                                           Movie
isim                                                       Deliha 2
yönetmen                                                 Gupse Özay
kadro             Gupse Özay, Eda Ece, Aksel Bonfil, Derya Alabo...
ülke                                                         Turkey
eklenme_tarihi                                   September 27, 2019
vizyon_tarihi                                                  2018
kanal                                                         TV-PG
süre                                                        102 min
kategori                             Comedies, International Movies
aciklama          While chasing her dream of becoming a chef, Ze...
Name: 100, dtype: object

In [15]:
df[['isim','yönetmen','kategori','süre']]

,isim,yönetmen,kategori,süre
0,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Children & Family Movies, Comedies",90 min
1,Jandino: Whatever it Takes,NaN,Stand-Up Comedy,94 min
2,Transformers Prime,NaN,Kids' TV,1 Season
3,Transformers: Robots in Disguise,NaN,Kids' TV,1 Season
4,#realityhigh,Fernando Lebrija,Comedies,99 min
...,...,...,...,...
6229,Red vs. Blue,NaN,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...",13 Seasons
6230,Maron,NaN,TV Comedies,4 Seasons
6231,Little Baby Bum: Nursery Rhyme Friends,NaN,Movies,60 min
6232,A Young Doctor's Notebook and Other Stories,NaN,"British TV Shows, TV Comedies, TV Dramas",2 Seasons
6233,Friends,NaN,"Classic & Cult TV, TV Comedies",10 Seasons

In [16]:
IMDB = np.random.uniform(low=3.0, high=9.2, size=len(df['isim']))
IMDB = np.around(IMDB,decimals = 1)

In [17]:
df['IMDB_puan'] = IMDB #Ürettigimiz rast gele puanlari "IMDB_puan" sütunu olarak ekleyelim.
df.head()

,show_nu,tip,isim,yönetmen,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6

In [18]:
del df['yönetmen']

In [19]:
df.head()

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6

In [20]:
df.drop('eklenme_tarihi',axis=1)

,show_nu,tip,isim,kadro,ülke,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6
...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.3
6230,70286564,TV Show,Maron,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",7.7
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,4.2
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.5
6233,70153404,TV Show,Friends,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,5.2

In [22]:
df['IMDB_puan'].agg(['max','min','mean'])

max     9.200000
min     3.000000
mean    6.096952
Name: IMDB_puan, dtype: float64

In [24]:
df['IMDB_puan'][df['IMDB_puan'] == 9.2].count() #imdb si 9.2 olan kaç tane  film

49

In [31]:
df['isim'][df['IMDB_puan'] == 9.2].head()

451              Private Life
783                      Blow
946       Justice in the City
951     My Life as a Zucchini
1107      True: Winter Wishes
Name: isim, dtype: object

In [33]:
df.sort_values(by = 'IMDB_puan', ascending = False)

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
3094,70295560,Movie,Bo Burnham: what.,Bo Burnham,United States,"July 1, 2018",2013,TV-MA,60 min,Stand-Up Comedy,Left brain and right brain duke it out – and u...,9.2
3273,70279637,Movie,Frozen Planet: On Thin Ice,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,47 min,Movies,David Attenborough journeys to both polar regi...,9.2
5119,80041339,Movie,The Diabolical,"Ali Larter, Arjun Gupta, Max Rose, Merrin Dung...",United States,"August 1, 2018",2015,TV-MA,86 min,"Horror Movies, Sci-Fi & Fantasy, Thrillers",Terrorized by unexplained disturbances and hor...,9.2
451,80168222,Movie,Private Life,"Paul Giamatti, Kathryn Hahn, Kayli Carter, Mol...",United States,"October 5, 2018",2018,R,124 min,"Comedies, Dramas, Independent Movies","Struggling to conceive, a couple in their 40s ...",9.2
4492,70224999,Movie,Don 2,"Shah Rukh Khan, Priyanka Chopra, Boman Irani, ...","India, Germany","December 15, 2019",2011,TV-14,148 min,"Action & Adventure, International Movies, Musi...","With Asia under his complete control, criminal...",9.2
...,...,...,...,...,...,...,...,...,...,...,...,...
5100,80997864,Movie,Little Dragon Maiden,"Leslie Cheung, Jing-Jing Yung, Chen Kuan-tai, ...",Hong Kong,"August 1, 2018",1983,TV-14,92 min,"Action & Adventure, International Movies, Roma...","Seeking to improve his combat skills, a young ...",3.0
83,80199032,TV Show,Paul Hollywood's Big Continental Road Trip,Paul Hollywood,United Kingdom,"September 29, 2017",2017,TV-14,1 Season,"British TV Shows, Docuseries, International TV...",Gear up for a fast-paced journey as celebrity ...,3.0
120,81186757,Movie,Oh! Baby (Tamil),"Samantha Ruth Prabhu, Lakshmi, Rajendraprasad,...",India,"September 25, 2019",2019,TV-14,146 min,"Comedies, International Movies, Music & Musicals",A surly septuagenarian gets another chance at ...,3.0
4056,80078037,TV Show,Little Lunch,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take...",3.0
991,60022914,Movie,Hard Lessons,"Denzel Washington, Lynn Whitfield, Richard Mas...",United States,"October 1, 2011",1986,NR,94 min,Dramas,This drama based on real-life events tells the...,3.0

In [34]:
df['IMDB_puan'].describe()

count    6234.000000
mean        6.096952
std         1.784949
min         3.000000
25%         4.500000
50%         6.100000
75%         7.600000
max         9.200000
Name: IMDB_puan, dtype: float64

In [39]:
df[(df['IMDB_puan']>8) & (df['ülke']=='Turkey')]

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
271,81132438,Movie,Locked on You,"Ata Demirer, Demet Akbağ, Gonca Vuslateri, İlk...",Turkey,"September 13, 2019",2018,TV-14,105 min,"Comedies, International Movies","When his chatty nature lands him in trouble, a...",9.1
2257,80134521,Movie,Berlin Kaplani,"Ata Demirer, Necati Bilgiç, Tarık Ünlüoğlu, Öz...",Turkey,"March 10, 2017",2012,TV-14,99 min,"Comedies, International Movies, Sports Movies","After a losing streak puts him in debt of 50,0...",8.7
2266,80038353,Movie,Eyyvah Eyyvah,"Demet Akbağ, Ata Demirer, Özge Borak, Bican Gü...",Turkey,"March 10, 2017",2010,TV-MA,99 min,"Comedies, International Movies",A clarinet player who lives with his grandpare...,8.6
2275,80134436,Movie,Kara Bela,"Cengiz Bozkurt, Seda Bakan, Erkan Kolçak Köste...",Turkey,"March 10, 2017",2015,TV-14,101 min,"Comedies, International Movies",The uneventful life of middle-aged Kudret turn...,8.9
2276,80134514,Movie,Kocan Kadar Konus,"Ezgi Mola, Murat Yıldırım, Gülenay Kalkan, Ebr...",Turkey,"March 10, 2017",2015,TV-14,104 min,"Comedies, International Movies, Romantic Movies",A 30-year-old who's never taken the traditiona...,8.7
2278,80134520,Movie,Kurtulus Son Durak,"Belçim Bilgin, Demet Akbağ, Asuman Dabak, Ayte...",Turkey,"March 10, 2017",2012,TV-MA,100 min,"Comedies, Dramas, International Movies",When a recently single psychologist moves to a...,9.1
4346,80037129,TV Show,Ezel,"Kenan İmirzalıoğlu, Cansu Dere, Haluk Bilginer...",Turkey,"December 26, 2016",2009,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",A young man framed for a crime escapes a priso...,8.9
4347,80037176,TV Show,Kaçak,"Gürkan Uygun, Mustafa Avkıran, Berk Hakman, Be...",Turkey,"December 26, 2016",2013,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Act...",A cop who killed a mobster's son and fled to a...,9.0
5223,80231064,Movie,Ali Baba ve 7 Cüceler,"Cem Yılmaz, Irina Ivkina, Çetin Altay, Zafer A...",Turkey,"April 4, 2018",2015,TV-MA,115 min,"Action & Adventure, Comedies, International Mo...",A garden gnome vendor and his brother-in-law a...,8.8
5224,80227118,Movie,Aşk Tesadüfleri Sever,"Mehmet Günsür, Belçim Bilgin, Ayda Aksel, Alta...",Turkey,"April 4, 2018",2011,TV-MA,122 min,"Dramas, International Movies, Romantic Movies",A series of coincidences brings two star-cross...,8.2
5450,81043541,Movie,Dabbe: The Possession,"Cansu Kurgun, Irmak Örnek, A. Murat Özgen, Sul...",Turkey,"April 12, 2019",2013,TV-MA,135 min,"Horror Movies, International Movies","Ahead of her wedding, Kübra is possessed by de...",8.1
5551,80123567,TV Show,Burned Cocoon,"Yavuz Bingöl, Basak Köklükaya, Çolpan Ilhan, M...",Turkey,"April 1, 2017",2005,TV-14,1 Season,"International TV Shows, TV Dramas",A secret marriage unites two families – one we...,8.8
6212,80126877,TV Show,Filinta,"Onur Tuna, Serhat Tutumluer, Mehmet Özgür, Naz...",Turkey,"April 15, 2017",2015,TV-14,2 Seasons,"Crime TV Shows, International TV Shows, TV Act...","In 19th-century Istanbul, a young police offic...",8.7

In [40]:
df['vizyon_tarihi'].min()

1925

In [41]:
df['vizyon_tarihi'].idxmin()

4292

In [42]:
df.loc[4292,'isim']

'Pioneers: First Women Filmmakers*'

In [44]:
df.isnull().sum()

show_nu             0
tip                 0
isim                0
kadro             570
ülke              476
eklenme_tarihi     11
vizyon_tarihi       0
kanal              10
süre                0
kategori            0
aciklama            0
IMDB_puan           0
dtype: int64

In [45]:
df.dropna()

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...
6218,80162994,TV Show,Talking Tom and Friends,"Colin Hanks, Tom Kenny, James Adomian, Lisa Sc...","Cyprus, Austria, Thailand","April 10, 2019",2017,TV-G,2 Seasons,"Kids' TV, TV Comedies",Full of funny one-liners and always ready for ...,8.9
6219,80186475,TV Show,Pokémon the Series,"Sarah Natochenny, Laurie Hymes, Jessica Paquet...",Japan,"April 1, 2019",2019,TV-Y7-FV,2 Seasons,"Anime Series, Kids' TV",Ash and his Pikachu travel to the Alola region...,3.5
6220,70272742,TV Show,Justin Time,"Gage Munroe, Scott McCord, Jenna Warren",Canada,"April 1, 2016",2012,TV-Y,2 Seasons,Kids' TV,"In Justin's dreams, he and his imaginary frien...",8.0
6221,80067942,TV Show,Terrace House: Boys & Girls in the City,"You, Reina Triendl, Ryota Yamasato, Yoshimi To...",Japan,"April 1, 2016",2016,TV-14,2 Seasons,"International TV Shows, Reality TV",A new set of six men and women start their liv...,4.6
6222,70136122,TV Show,Weeds,"Mary-Louise Parker, Hunter Parrish, Alexander ...",United States,"April 1, 2014",2012,TV-MA,8 Seasons,"TV Comedies, TV Dramas",A suburban mother starts selling marijuana to ...,7.8

In [46]:
df.fillna(value ='mevcut degil')

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,mevcut degil,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.3
6230,70286564,TV Show,Maron,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,mevcut degil,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",7.7
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,mevcut degil,mevcut degil,mevcut degil,2016,mevcut degil,60 min,Movies,Nursery rhymes and original music for children...,4.2
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,mevcut degil,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.5
6233,70153404,TV Show,Friends,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,mevcut degil,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,5.2

In [47]:
df.fillna(method = 'ffill')

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Show,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Show,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Show,Red vs. Blue,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,"April 1, 2014",2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.3
6230,70286564,TV Show,Maron,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,"April 1, 2014",2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",7.7
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,"April 1, 2014",2016,TV-MA,60 min,Movies,Nursery rhymes and original music for children...,4.2
6232,70281022,TV Show,A Young Doctor's Notebook and Other Stories,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,"April 1, 2014",2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.5
6233,70153404,TV Show,Friends,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,"April 1, 2014",2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,5.2

In [48]:
df['tip'].unique()

array(['Movie', 'TV Show'], dtype=object)

In [49]:
df['kanal'].unique()

array(['TV-PG', 'TV-MA', 'TV-Y7-FV', 'TV-Y7', 'TV-14', 'R', 'TV-Y', 'NR',
       'PG-13', 'TV-G', 'PG', 'G', nan, 'UR', 'NC-17'], dtype=object)

In [50]:
pd.crosstab(df['tip'],df['kanal'])

kanal,G,NC-17,NR,PG,PG-13,R,TV-14,TV-G,TV-MA,TV-PG,TV-Y,TV-Y7,TV-Y7-FV,UR
tip,,,,,,,,,,,,,,
Movie,36,2,202,183,286,506,1038,80,1348,432,41,69,27,7
TV Show,1,0,16,1,0,2,660,69,679,269,102,100,68,0

In [51]:
df.replace({'tip': {'movie' : 'Film', 'TV Show': 'TV Programi'}})

,show_nu,tip,isim,kadro,ülke,eklenme_tarihi,vizyon_tarihi,kanal,süre,kategori,aciklama,IMDB_puan
0,81145628,Movie,Norm of the North: King Sized Adventure,"Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...,4.9
1,80117401,Movie,Jandino: Whatever it Takes,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...,5.3
2,70234439,TV Programi,Transformers Prime,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob...",6.9
3,80058654,TV Programi,Transformers: Robots in Disguise,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...,7.2
4,80125979,Movie,#realityhigh,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...
6229,80000063,TV Programi,Red vs. Blue,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil...",3.3
6230,70286564,TV Programi,Maron,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews...",7.7
6231,80116008,Movie,Little Baby Bum: Nursery Rhyme Friends,NaN,NaN,NaN,2016,NaN,60 min,Movies,Nursery rhymes and original music for children...,4.2
6232,70281022,TV Programi,A Young Doctor's Notebook and Other Stories,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ...",3.5
6233,70153404,TV Programi,Friends,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...,5.2

In [52]:
grup = df['IMDB_puan'].groupby(df['kanal'])

In [53]:
grup

In [54]:
grup.mean().sort_values()#kanalları ortalama IMDB puanlarına göre sıralama

kanal
TV-G        5.999329
TV-PG       6.013980
PG-13       6.025524
PG          6.054348
R           6.069488
NR          6.087615
TV-Y7       6.099408
TV-14       6.112485
TV-MA       6.123088
UR          6.142857
TV-Y        6.189510
G           6.310811
TV-Y7-FV    6.409474
NC-17       6.500000
Name: IMDB_puan, dtype: float64

In [57]:
def ikiyebol(ser):
   return ser/2.0

In [59]:
df['IMDB_puan'].apply(ikiyebol)

0       2.45
1       2.65
2       3.45
3       3.60
4       1.80
        ...
6229    1.65
6230    3.85
6231    2.10
6232    1.75
6233    2.60
Name: IMDB_puan, Length: 6234, dtype: float64